# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f094684cf16bb9db94041795c09863c1747d8f4e7ef70edb31fa819bda5bd5ea6b498236c1674e046378ab342c7f48d76d2e248f04faef9a9157445906a28c0d

test:
  secret_key_base: 59b77f22e756de1b310e10fc36ac158ce8cee747f7a08f9b000904d7647b470f50f27d6cb28623cd509b361d23b223e2a8541711adf843a07acb25030e409572

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
